Show a spinner while pulling an image from the registry using buildah

diff --git a/fedora-toolbox b/fedora-toolbox
--- a/fedora-toolbox
+++ b/fedora-toolbox
@@ -128,9 +128,26 @@ create()
                      localhost/$base_toolbox_image >/dev/null 2>&42; then
             echo "$0: looking for image $registry/$fgc/$base_toolbox_image" >&42
 
-            if ! $prefix_sudo buildah from \
-                         --name $working_container_name \
-                         $registry/$fgc/$base_toolbox_image >/dev/null 2>&42; then
+            if spinner_directory=$(mktemp --directory --tmpdir fedora-toolbox-spinner-XXXXXXXXXX 2>&42); then
+                spinner_message="$0: pulling from $registry: "
+                if ! spinner_start "$spinner_directory" "$spinner_message"; then
+                    spinner_directory=""
+                fi
+            else
+                echo "$0: unable to start spinner: spinner directory not created"
+                spinner_directory=""
+            fi
+
+            $prefix_sudo buildah from \
+                    --name $working_container_name \
+                    $registry/$fgc/$base_toolbox_image >/dev/null 2>&42
+            ret_val=$?
+
+            if [ "$spinner_directory" != "" ]; then
+                spinner_stop "$spinner_directory"
+            fi
+
+            if [ $ret_val -ne 0 ]; then
                 echo "$0: failed to create working container"
                 exit 1
             fi
