Show a spinner while creating the toolbox container using podman

diff --git a/fedora-toolbox b/fedora-toolbox
--- a/fedora-toolbox
+++ b/fedora-toolbox
@@ -262,26 +262,43 @@ create()
 
     echo "$0: trying to create container $toolbox_container" >&42
 
-    if ! $prefix_sudo podman create \
-                 --group-add wheel \
-                 --hostname toolbox \
-                 --interactive \
-                 --name $toolbox_container \
-                 --network host \
-                 --privileged \
-                 --security-opt label=disable \
-                 --tmpfs /dev/shm:size=$tmpfs_size \
-                 --tty \
-                 --uidmap $UID:0:1 \
-                 --uidmap 0:1:$UID \
-                 --uidmap $uid_plus_one:$uid_plus_one:$max_minus_uid \
-                 --volume $HOME:$HOME \
-                 --volume $XDG_RUNTIME_DIR:$XDG_RUNTIME_DIR \
-                 --volume $dbus_system_bus_path:$dbus_system_bus_path \
-                 --volume /dev/dri:/dev/dri \
-                 --volume /dev/fuse:/dev/fuse \
-                 $toolbox_image \
-                 /bin/sh >/dev/null 2>&42; then
+    if spinner_directory=$(mktemp --directory --tmpdir fedora-toolbox-spinner-XXXXXXXXXX 2>&42); then
+        spinner_message="$0: creating container $toolbox_container: "
+        if ! spinner_start "$spinner_directory" "$spinner_message"; then
+            spinner_directory=""
+        fi
+    else
+        echo "$0: unable to start spinner: spinner directory not created"
+        spinner_directory=""
+    fi
+
+    $prefix_sudo podman create \
+            --group-add wheel \
+            --hostname toolbox \
+            --interactive \
+            --name $toolbox_container \
+            --network host \
+            --privileged \
+            --security-opt label=disable \
+            --tmpfs /dev/shm:size=$tmpfs_size \
+            --tty \
+            --uidmap $UID:0:1 \
+            --uidmap 0:1:$UID \
+            --uidmap $uid_plus_one:$uid_plus_one:$max_minus_uid \
+            --volume $HOME:$HOME \
+            --volume $XDG_RUNTIME_DIR:$XDG_RUNTIME_DIR \
+            --volume $dbus_system_bus_path:$dbus_system_bus_path \
+            --volume /dev/dri:/dev/dri \
+            --volume /dev/fuse:/dev/fuse \
+            $toolbox_image \
+            /bin/sh >/dev/null 2>&42
+    ret_val=$?
+
+    if [ "$spinner_directory" != "" ]; then
+        spinner_stop "$spinner_directory"
+    fi
+
+    if [ $ret_val -ne 0 ]; then
         echo "$0: failed to create container $toolbox_container"
         exit 1
     fi
