Clarify the error message if the container already exists

diff --git a/fedora-toolbox b/fedora-toolbox
--- a/fedora-toolbox
+++ b/fedora-toolbox
@@ -90,27 +90,32 @@ create()
         fi
     fi
 
-    max_uid_count=65536
-    max_minus_uid=$((max_uid_count-UID))
-    uid_plus_one=$((UID+1))
-    if ! $prefix_sudo podman create \
-                 --group-add wheel \
-                 --hostname toolbox \
-                 --interactive \
-                 --name $toolbox_container \
-                 --network host \
-                 --privileged \
-                 --security-opt label=disable \
-                 --tty \
-                 --uidmap $UID:0:1 \
-                 --uidmap 0:1:$UID \
-                 --uidmap $uid_plus_one:$uid_plus_one:$max_minus_uid \
-                 --volume $HOME:$HOME \
-                 --volume $XDG_RUNTIME_DIR:$XDG_RUNTIME_DIR \
-                 $toolbox_image \
-                 /bin/sh >/dev/null 2>&42; then
-        echo "$0: failed to create container $toolbox_container"
+    if $prefix_sudo podman inspect --type container $toolbox_container >/dev/null 2>&42; then
+        echo "$0: container $toolbox_container already exists"
         exit 1
+    else
+        max_uid_count=65536
+        max_minus_uid=$((max_uid_count-UID))
+        uid_plus_one=$((UID+1))
+        if ! $prefix_sudo podman create \
+                     --group-add wheel \
+                     --hostname toolbox \
+                     --interactive \
+                     --name $toolbox_container \
+                     --network host \
+                     --privileged \
+                     --security-opt label=disable \
+                     --tty \
+                     --uidmap $UID:0:1 \
+                     --uidmap 0:1:$UID \
+                     --uidmap $uid_plus_one:$uid_plus_one:$max_minus_uid \
+                     --volume $HOME:$HOME \
+                     --volume $XDG_RUNTIME_DIR:$XDG_RUNTIME_DIR \
+                     $toolbox_image \
+                     /bin/sh >/dev/null 2>&42; then
+            echo "$0: failed to create container $toolbox_container"
+            exit 1
+        fi
     fi
 )
 
