Show a spinner while configuring the working container using buildah

diff --git a/fedora-toolbox b/fedora-toolbox
--- a/fedora-toolbox
+++ b/fedora-toolbox
@@ -229,7 +229,24 @@ create()
 
         echo "$0: trying to configure working container $working_container_name" >&42
 
-        if ! configure_working_container $working_container_name; then
+        if spinner_directory=$(mktemp --directory --tmpdir fedora-toolbox-spinner-XXXXXXXXXX 2>&42); then
+            spinner_message="$0: configuring working container: "
+            if ! spinner_start "$spinner_directory" "$spinner_message"; then
+                spinner_directory=""
+            fi
+        else
+            echo "$0: unable to start spinner: spinner directory not created"
+            spinner_directory=""
+        fi
+
+        configure_working_container $working_container_name
+        ret_val=$?
+
+        if [ "$spinner_directory" != "" ]; then
+            spinner_stop "$spinner_directory"
+        fi
+
+        if [ $ret_val -ne 0 ]; then
             $prefix_sudo buildah rm $working_container_name >/dev/null 2>&42
             exit 1
         fi
