Ensure correct toolbox.sh is used by container
This fix an issue where /etc/profile.d/toolbox.sh was mounted inside the
container, which may happen with containers created with some previous
versions of toolbox, and then when entering the container toolbox would
not copy the latest version of the file to the container and the mounted
version would be used instead.

Without this change, some issues fixed (e.g. line wrapping on long
input [1]) in the current /etc/profile.d/toolbox.sh could not be applied
to these containers depending on the version of it that was mounted in
the container.

[1] Commit bc1a816ea3b80fc7c3dc5d523838256e94c953d2
    https://github.com/debarshiray/toolbox/issues/190

Signed-off-by: Andre Moreira Magalhaes <andre@endlessm.com>

diff --git a/toolbox b/toolbox
--- a/toolbox
+++ b/toolbox
@@ -1117,28 +1117,35 @@ run()
 
     echo "$base_toolbox_command: starting container $toolbox_container" >&3
 
+    echo "$base_toolbox_command: checking if /etc/profile.d/toolbox.sh is mounted in container $toolbox_container." >&3
+
     if is_etc_profile_d_toolbox_a_bind_mount "$toolbox_container"; then
-        echo "$base_toolbox_command: /etc/profile.d/toolbox.sh already mounted in container $toolbox_container" >&3
+        echo "$base_toolbox_command: /etc/profile.d/toolbox.sh is mounted in container $toolbox_container. Umounting to ensure correct version is used." >&3
+
+        if ! $prefix_sudo podman exec --user root:root "$toolbox_container" umount /etc/profile.d/toolbox.sh 2>&3; then
+            echo "$base_toolbox_command: failed to umount /etc/profile.d/toolbox.sh inside container" >&2
+            exit 1
+        fi
 
         if ! $prefix_sudo podman start "$toolbox_container" >/dev/null 2>&3; then
             echo "$base_toolbox_command: failed to start container $toolbox_container" >&2
             exit 1
         fi
     else
-        echo "$base_toolbox_command: /etc/profile.d/toolbox.sh not mounted in container $toolbox_container" >&3
+        echo "$base_toolbox_command: /etc/profile.d/toolbox.sh is not mounted in container $toolbox_container" >&3
+    fi
 
-        if ! copy_etc_profile_d_toolbox_to_runtime_directory; then
-            exit 1
-        fi
+    if ! copy_etc_profile_d_toolbox_to_runtime_directory; then
+        exit 1
+    fi
 
-        if ! $prefix_sudo podman start "$toolbox_container" >/dev/null 2>&3; then
-            echo "$base_toolbox_command: failed to start container $toolbox_container" >&2
-            exit 1
-        fi
+    if ! $prefix_sudo podman start "$toolbox_container" >/dev/null 2>&3; then
+        echo "$base_toolbox_command: failed to start container $toolbox_container" >&2
+        exit 1
+    fi
 
-        if ! copy_etc_profile_d_toolbox_to_container "$toolbox_container"; then
-            exit 1
-        fi
+    if ! copy_etc_profile_d_toolbox_to_container "$toolbox_container"; then
+        exit 1
     fi
 
     if ! $prefix_sudo podman exec --user root:root "$toolbox_container" touch /run/.toolboxenv 2>&3; then
