Include images tagged with c.gh.debarshiray.toolbox in 'list'
Commit 0ab6eb7401fb3964 introduced the com.github.debarshiray.toolbox
label as a better way to identify toolbox containers and images. Images
having that label should be included in 'toolbox list'.

Since 'podman images' re-formats the creation time (ie., {{.Created}})
into a human-readable form (eg., 34 seconds ago), successive
'podman images' invocations might have slightly different strings for
the same image. This becomes a problem for images that have both the
com.github.debarshiray.toolbox and com.redhat.component tags. If they
have slightly different entries for the creation time, sort(1) and
uniq(1) won't consider them as the same entry.

Moreoever, specifying multiple filters will only match images that have
both tags, instead of images that have either one of them. This will
break compatibility with older images that didn't have the
com.github.debarshiray.toolbox label.

Therefore, the images are queried as two separate lists without the
creation time. The creation time is queried in a separate step once the
two separate lists of images have been merged into one. To ensure some
human-understandable ordering, the lists are merged based on the image
names, not the image IDs.

https://github.com/debarshiray/toolbox/pull/91

diff --git a/toolbox b/toolbox
--- a/toolbox
+++ b/toolbox
@@ -405,6 +405,26 @@ image_reference_has_domain()
 )
 
 
+images_get_details()
+(
+    images="$1"
+
+    if ! echo "$images" | while read -r image; do
+            if ! $prefix_sudo podman images \
+                         --format "{{.ID}} {{.Repository}}:{{.Tag}} {{.Created}}" \
+                         --noheading \
+                         "$image" 2>&3; then
+                echo "$base_toolbox_command: failed to get details for image $image" >&2
+                return 1
+            fi
+         done; then
+        return 1
+    fi
+
+    return 0
+)
+
+
 pull_base_toolbox_image()
 (
     has_domain=false
@@ -732,14 +752,26 @@ enter()
 
 list_images()
 (
-    if ! images=$($prefix_sudo podman images \
-                          --filter "label=com.redhat.component=fedora-toolbox" \
-                          --format "{{.ID}} {{.Repository}}:{{.Tag}} {{.Created}}" 2>&3); then
-        echo "$base_toolbox_command: failed to list images" >&2
+    if ! images_old=$($prefix_sudo podman images \
+                              --filter "label=com.redhat.component=fedora-toolbox" \
+                              --format "{{.Repository}}:{{.Tag}}" 2>&3); then
+        echo "$base_toolbox_command: failed to list images with com.redhat.component=fedora-toolbox" >&2
         return 1
     fi
 
-    if ! output=$(echo "$images" \
+    if ! images=$($prefix_sudo podman images \
+                          --filter "label=com.github.debarshiray.toolbox=true" \
+                          --format "{{.Repository}}:{{.Tag}}" 2>&3); then
+        echo "$base_toolbox_command: failed to list images with com.github.debarshiray.toolbox=true" >&2
+        return 1
+    fi
+
+    images=$(printf "%s\n%s\n" "$images_old" "$images" | sort 2>&3 | uniq 2>&3)
+    if ! details=$(images_get_details "$images"); then
+        return 1
+    fi
+
+    if ! output=$(echo "$details" \
                   | sed "s/ \{2,\}/\t/g" 2>&3 \
                   | column --separator "$tab" --table --table-columns "IMAGE ID,IMAGE NAME,CREATED" 2>&3); then
         echo "$base_toolbox_command: failed to parse list of images" >&2
