Add a helper function to bind mount locations at runtime
Subsequent commits will use this to perform some of the bind mounts in
the toolbox container's entry point, instead of doing them as part of
'podman create ...'.

Anything that's specified during 'podman create ...' gets statically
baked into the container's configuration, and is either difficult or
impossible to change afterwards. This means that toolbox containers
created with older versions of Toolbox keep diverging from those
created with newer versions. Hence making it complicated to keep older
containers working with a newer Toolbox.

In the case of bind mounts, a good chunk of the host's file hierarchy
is already bind mounted by 'podman create ...' under the toolbox
container's /run/host. Therefore, the more granular bind mounts like
$XDG_RUNTIME_DIR and /var/lib/flatpak can be performed by the
container's entry point at runtime using what's already inside
/run/host, and reduce the footprint of the static configuration.

Older containers created with Toolbox 0.0.10 onwards will see two bind
mounts for locations that get moved from 'podman create ...' to the
entry point. The presence of the second mount should be harmless.

Based on an idea from Colin Walters.

https://github.com/containers/toolbox/pull/327

diff --git a/toolbox b/toolbox
--- a/toolbox
+++ b/toolbox
@@ -672,6 +672,39 @@ list_container_names()
 )
 
 
+mount_bind()
+(
+    source="$1"
+    target="$2"
+    mount_flags="$3"
+
+    mount_o=""
+
+    ! [ -d "$source" ] 2>&3 && ! [ -f "$source" ] 2>&3 && return 0
+
+    if [ -d "$source" ] 2>&3; then
+        echo "$base_toolbox_command: creating $target" >&3
+
+        if ! mkdir --parents "$target" 2>&3; then
+            echo "$base_toolbox_command: failed to create $target" >&2
+            return 1
+        fi
+    fi
+
+    echo "$base_toolbox_command: binding $target to $source" >&3
+
+    [ "$mount_flags" = "" ] 2>&3 || mount_o="-o $mount_flags"
+
+    # shellcheck disable=SC2086
+    if ! mount --bind $mount_o "$source" "$target" 2>&3; then
+        echo "$base_toolbox_command: failed to bind $target to $source" >&2
+        return 1
+    fi
+
+    return 0
+)
+
+
 pull_base_toolbox_image()
 (
     domain=""
