Unbreak /etc/localtime & /etc/timezone if /run/host/monitor is absent
Toolbox containers created prior to commit 8db414ddc2d73719 didn't have
/run/host/monitor inside them. Therefore, those containers were having
their /etc/localtime and /etc/timezone redirected to locations that
didn't exist.

Instead of selectively checking locations that were added later, it's
more manageable to handle all bind mounted target locations the same.

https://github.com/debarshiray/toolbox/pull/207

diff --git a/toolbox b/toolbox
--- a/toolbox
+++ b/toolbox
@@ -875,57 +875,63 @@ init_container()
     if $init_container_monitor_host; then
         working_directory="$PWD"
 
-        if ! readlink /etc/host.conf >/dev/null 2>&3; then
-            echo "$base_toolbox_command: redirecting /etc/host.conf to /run/host/etc/host.conf" >&3
+        if [ -d /run/host/etc ] 2>&3; then
+            if ! readlink /etc/host.conf >/dev/null 2>&3; then
+                echo "$base_toolbox_command: redirecting /etc/host.conf to /run/host/etc/host.conf" >&3
 
-            if ! (cd /etc 2>&3 \
-                  && unlink host.conf 2>&3 \
-                  && ln --symbolic /run/host/etc/host.conf host.conf 2>&3); then
-                echo "$base_toolbox_command: failed to redirect /etc/host.conf to /run/host/etc/host.conf" >&2
-                return 1
+                if ! (cd /etc 2>&3 \
+                      && unlink host.conf 2>&3 \
+                      && ln --symbolic /run/host/etc/host.conf host.conf 2>&3); then
+                    echo "$base_toolbox_command: failed to redirect /etc/host.conf to /run/host/etc/host.conf" >&2
+                    return 1
+                fi
+            fi
+
+            if ! readlink /etc/hosts >/dev/null 2>&3; then
+                echo "$base_toolbox_command: redirecting /etc/hosts to /run/host/etc/hosts" >&3
+
+                if ! (cd /etc 2>&3 && unlink hosts 2>&3 && ln --symbolic /run/host/etc/hosts hosts 2>&3); then
+                    echo "$base_toolbox_command: failed to redirect /etc/hosts to /run/host/etc/hosts" >&2
+                    return 1
+                fi
+            fi
+
+            if ! readlink /etc/resolv.conf >/dev/null 2>&3; then
+                echo "$base_toolbox_command: redirecting /etc/resolv.conf to /run/host/etc/resolv.conf" >&3
+
+                if ! (cd /etc 2>&3 \
+                      && unlink resolv.conf 2>&3 \
+                      && ln --symbolic /run/host/etc/resolv.conf resolv.conf 2>&3); then
+                    echo "$base_toolbox_command: failed to redirect /etc/resolv.conf to /run/host/etc/resolv.conf" \
+                            >&2
+                    return 1
+                fi
             fi
         fi
 
-        if ! readlink /etc/hosts >/dev/null 2>&3; then
-            echo "$base_toolbox_command: redirecting /etc/hosts to /run/host/etc/hosts" >&3
+        if [ -d /run/host/monitor ] 2>&3; then
+            if ! localtime_target=$(readlink /etc/localtime >/dev/null 2>&3) \
+               || [ "$localtime_target" != "/run/host/monitor/localtime" ] 2>&3; then
+                echo "$base_toolbox_command: redirecting /etc/localtime to /run/host/monitor/localtime" >&3
 
-            if ! (cd /etc 2>&3 && unlink hosts 2>&3 && ln --symbolic /run/host/etc/hosts hosts 2>&3); then
-                echo "$base_toolbox_command: failed to redirect /etc/hosts to /run/host/etc/hosts" >&2
-                return 1
+                if ! (cd /etc 2>&3 \
+                      && unlink localtime 2>&3 \
+                      && ln --symbolic /run/host/monitor/localtime localtime 2>&3); then
+                    echo "$base_toolbox_command: failed to redirect /etc/localtime to /run/host/monitor/localtime" \
+                            >&2
+                    return 1
+                fi
             fi
-        fi
 
-        if ! localtime_target=$(readlink /etc/localtime >/dev/null 2>&3) \
-           || [ "$localtime_target" != "/run/host/monitor/localtime" ] 2>&3; then
-            echo "$base_toolbox_command: redirecting /etc/localtime to /run/host/monitor/localtime" >&3
+            if ! readlink /etc/timezone >/dev/null 2>&3; then
+                echo "$base_toolbox_command: redirecting /etc/timezone to /run/host/monitor/timezone" >&3
 
-            if ! (cd /etc 2>&3 \
-                  && unlink localtime 2>&3 \
-                  && ln --symbolic /run/host/monitor/localtime localtime 2>&3); then
-                echo "$base_toolbox_command: failed to redirect /etc/localtime to /run/host/monitor/localtime" >&2
-                return 1
-            fi
-        fi
-
-        if ! readlink /etc/resolv.conf >/dev/null 2>&3; then
-            echo "$base_toolbox_command: redirecting /etc/resolv.conf to /run/host/etc/resolv.conf" >&3
-
-            if ! (cd /etc 2>&3 \
-                  && unlink resolv.conf 2>&3 \
-                  && ln --symbolic /run/host/etc/resolv.conf resolv.conf 2>&3); then
-                echo "$base_toolbox_command: failed to redirect /etc/resolv.conf to /run/host/etc/resolv.conf" >&2
-                return 1
-            fi
-        fi
-
-        if ! readlink /etc/timezone >/dev/null 2>&3; then
-            echo "$base_toolbox_command: redirecting /etc/timezone to /run/host/monitor/timezone" >&3
-
-            if ! (cd /etc 2>&3 \
-                  && rm --force timezone 2>&3 \
-                  && ln --symbolic /run/host/monitor/timezone timezone 2>&3); then
-                echo "$base_toolbox_command: failed to redirect /etc/timezone to /run/host/monitor/timezone" >&2
-                return 1
+                if ! (cd /etc 2>&3 \
+                      && rm --force timezone 2>&3 \
+                      && ln --symbolic /run/host/monitor/timezone timezone 2>&3); then
+                    echo "$base_toolbox_command: failed to redirect /etc/timezone to /run/host/monitor/timezone" >&2
+                    return 1
+                fi
             fi
         fi
 
