Avoid a Bash-ism (ie. UID) and stick to POSIX (ie. id -ru)
Detected by the checkbashisms [1] tool.

[1] https://packages.debian.org/sid/devscripts

https://github.com/debarshiray/toolbox/issues/53

diff --git a/toolbox b/toolbox
--- a/toolbox
+++ b/toolbox
@@ -54,6 +54,7 @@ spinner_template="toolbox-spinner-XXXXXXXXXX"
 toolbox_container=""
 toolbox_image=""
 toolbox_prompt="🔹[\u@\h \W]\\$ "
+user_id_real=$(id -ru 2>&3)
 verbose=false
 
 
@@ -216,11 +217,11 @@ configure_working_container()
                  --home-dir $HOME \
                  --no-create-home \
                  --shell $SHELL \
-                 --uid $UID \
+                 --uid $user_id_real \
                  --groups wheel \
                  $USER \
                  >/dev/null 2>&3; then
-        echo "$base_toolbox_command: failed to create user $USER with UID $UID" >&2
+        echo "$base_toolbox_command: failed to create user $USER with UID $user_id_real" >&2
         return 1
     fi
 
@@ -382,8 +383,8 @@ create()
     fi
 
     max_uid_count=65536
-    max_minus_uid=$((max_uid_count - UID))
-    uid_plus_one=$((UID + 1))
+    max_minus_uid=$((max_uid_count - user_id_real))
+    uid_plus_one=$((user_id_real + 1))
 
     echo "$base_toolbox_command: trying to create container $toolbox_container" >&3
 
@@ -408,8 +409,8 @@ create()
             --security-opt label=disable \
             --tmpfs /dev/shm:size=$tmpfs_size \
             --tty \
-            --uidmap $UID:0:1 \
-            --uidmap 0:1:$UID \
+            --uidmap $user_id_real:0:1 \
+            --uidmap 0:1:$user_id_real \
             --uidmap $uid_plus_one:$uid_plus_one:$max_minus_uid \
             --volume $HOME:$HOME:rslave \
             --volume $XDG_RUNTIME_DIR:$XDG_RUNTIME_DIR \
