Handle errors in command pipeline when listing containers
Listing toolbox containers involves parsing the output of 'podman ps'
and rearranging the columns into a table. Parsing and rearranging
output is inherently brittle, and there's no guarantee that podman
itself won't fail. Therefore, it's prudent to sprinkle some error
handling.

diff --git a/toolbox b/toolbox
--- a/toolbox
+++ b/toolbox
@@ -485,15 +485,23 @@ list_images()
 
 list_containers()
 (
-    output=$($prefix_sudo podman ps \
-                     --all \
-                     --filter "label=com.redhat.component=fedora-toolbox" \
-                     --format "{{.ID}}  {{.Names}}  {{.Created}}  {{.Status}}  {{.Image}}" 2>&3 \
-             | sed "s/ \{2,\}/\t/g" 2>&3 \
-             | column \
-                       --separator $'\t' \
-                       --table \
-                       --table-columns "CONTAINER ID,CONTAINER NAME,CREATED,STATUS,IMAGE NAME" 2>&3)
+    if ! containers=$($prefix_sudo podman ps \
+                              --all \
+                              --filter "label=com.redhat.component=fedora-toolbox" \
+                              --format "{{.ID}}  {{.Names}}  {{.Created}}  {{.Status}}  {{.Image}}" 2>&3); then
+        echo "$base_toolbox_command: failed to list containers"
+        return 1
+    fi
+
+    if ! output=$(echo "$containers" \
+                  | sed "s/ \{2,\}/\t/g" 2>&3 \
+                  | column \
+                            --separator $'\t' \
+                            --table \
+                            --table-columns "CONTAINER ID,CONTAINER NAME,CREATED,STATUS,IMAGE NAME" 2>&3); then
+        echo "$base_toolbox_command: failed to parse list of containers"
+        return 1
+    fi
 
     if [ "$output" != "" ]; then
         echo -e "${LBC}Containers created by toolbox${NC}"
@@ -512,6 +520,8 @@ list_containers()
                   done
               )
     fi
+
+    return 0
 )
 
 
