Keep /etc/host.conf synchronized with the host
https://github.com/debarshiray/toolbox/issues/70

diff --git a/toolbox b/toolbox
--- a/toolbox
+++ b/toolbox
@@ -816,6 +816,15 @@ init_container()
     if $init_container_monitor_host; then
         working_directory="$PWD"
 
+        if ! readlink /etc/host.conf >/dev/null 2>&3; then
+            if ! (cd /etc 2>&3 \
+                  && unlink host.conf 2>&3 \
+                  && ln --symbolic /run/host/etc/host.conf host.conf 2>&3); then
+                echo "$base_toolbox_command: failed to redirect /etc/host.conf to /run/host/etc/host.conf" >&2
+                return 1
+            fi
+        fi
+
         if ! readlink /etc/hosts >/dev/null 2>&3; then
             if ! (cd /etc 2>&3 && unlink hosts 2>&3 && ln --symbolic /run/host/etc/hosts hosts 2>&3); then
                 echo "$base_toolbox_command: failed to redirect /etc/hosts to /run/host/etc/hosts" >&2
