cmd/run, sh: Show an error if $PWD is missing inside the container
It might happen that the current working directory in the present
environment is missing inside the container that's going to be used.
So far, Toolbox would fail silently, which wasn't very obvious.

Some changes by Debarshi Ray and Harry Míchal.

https://github.com/containers/toolbox/issues/369

diff --git a/toolbox b/toolbox
--- a/toolbox
+++ b/toolbox
@@ -1603,6 +1603,16 @@ run()
 
     $emit_escape_sequence && printf "\033]777;container;pop;;\033\\"
 
+    if [ "$ret_val" -eq 127 ] 2>&3; then
+        # shellcheck disable=SC2016
+        if ! $podman_command exec \
+                     --user "$USER" \
+                     "$toolbox_container" \
+                     sh -c 'test -d "$1"' sh "$PWD" >/dev/null 2>&3; then
+            echo "$base_toolbox_command: directory '$PWD' not found in container $toolbox_container" >&2
+        fi
+    fi
+
     exit "$ret_val"
 )
 
