images/fedora: Ensure that documentation and translations are present
This should finally ensure that the fedora-toolbox image doesn't have
any package that had its content, such as documentation or translations,
stripped out by the fedora base image.

Until now, missing-docs had a hand-maintained list of packages that had
their content stripped out by the fedora base image.  These packages are
reinstalled when building the fedora-toolbox image to restore the lost
content.  Unfortunately, this list was incomplete because it was only
updated when someone noticed that something is missing.

Now, the list is generated with:
  $ rpm --all --query --state --queryformat "PACKAGE: %{NAME}\n"

... to ensure that it's always complete.

The existing built-in test to ensure that the desired files are actually
present in the final image was extended to cover some of those that were
absent.  A new built-in test, based on the above rpm(1) command, was
added as a fallback to ensure that the final image doesn't have any
package with missing content.

Only the images for currently maintained Fedoras (ie., 37, 38 and 39)
were updated.

As suggested by Brian Campbell.

https://github.com/containers/toolbox/issues/603

diff --git a/images/fedora/f38/Containerfile b/images/fedora/f38/Containerfile
--- a/images/fedora/f38/Containerfile
+++ b/images/fedora/f38/Containerfile
@@ -41,4 +41,14 @@ RUN ret_val=0; \
   fi
 RUN rm /ensure-files
 
+RUN broken_packages="$(rpm --all --query --state --queryformat "PACKAGE: %{NAME}\n" \
+  | sed --quiet --regexp-extended '/PACKAGE: /{s/PACKAGE: // ; h ; b }; /^not installed/ { g; p }' \
+  | uniq \
+  | sort)"; \
+  if [ "$broken_packages" != "" ]; then \
+    echo "Packages with missing files:" >&2; \
+    echo "$broken_packages" >&2; \
+    false; \
+  fi
+
 RUN dnf clean all
